### ISSUE TITLE
wldd panic

### ISSUE THREAD

**Issue by Dalan94** [marcoesposito1988/dependency_runner#3]
Wldd panic when launching:
```
➜  /tmp RUST_BACKTRACE=1 ./wldd   
thread 'main' panicked at 'Argument `help` is undefined', /cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/command.rs:246:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: clap::builder::command::Command::mut_arg
   3: <wldd::WlddCli as clap::derive::CommandFactory>::command
   4: wldd::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

To let it work, I deleted the line 15 in wldd.rs.

**Comment by marcoesposito1988** [comment]
Great catch, thanks! It is fixed in version 1.2.4
